# 线上配置文件
# @author   小赵学Java
#    
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.204.128.198:3306/huizhi_answer?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootroot
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 3
    host: 47.115.230.253
    port: 6379
    timeout: 5000
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''

